name: Cypress Tests
on:
  push:
    branches:
      - main # Altere para o nome da sua branch principal

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Altere para a versão do Node.js desejada

      - name: Install Dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          record: true
          wait-on: 'http://automationpractice.com/' # Altere para o endereço correto do seu aplicativo
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}