name: Cypress Tests and Allure Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
            env: true
        env:
            email: ${{ secrets.email }}
            senha: ${{ secrets.senha }}

