name: End-to-end tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies including faker        
        run: |    
          npm install
          npm install faker --save-dev

      - name: Set environment variable
        run: |
          PASSWORD=$(cat cypress.env.json | jq -r '.senha')
          echo "PASSWORD=$PASSWORD" >> $GITHUB_ENV
  
      - name: Run Cypress
        run: npx cypress run