name: Executar testes básicos

on:
  push:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências do projeto
        run: npm install

      - name: Executar testes
        uses: cypress-io/github-actions@v5