name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
  
      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
  
      - name: Install Dependencies
        run: npm install
  
      - name: Run test
        run: npx cypress run || true
  

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore
          
      - uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore