name: End-to-end tests

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    name: Cypress Test Run
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
  
      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
  
      - name: Install Dependencies
        run: npm install
  
      - name: Run test
        run: npx cypress run || true

      - name: Upload Cypress Screenshots
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore